# Generated by Django 4.0.3 on 2022-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0003_rename_task_tasktab'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktab',
            name='date',
            field=models.DateField(default='2022-02-02'),
            preserve_default=False,
        ),
    ]
